### ISSUE TITLE
plugins - sakura - config

### ISSUE THREAD

**Issue by liuguoxings** [JabinPeng/vuepress-plugin-sakura#1]
num 和 zIndex 貌似没有作用

**Comment by JabinPeng** [comment]
可以截图看看你怎么写的配置  安装的版本是1.1.0吗

配置我调试过呢
 ["sakura", {
      num: 50,  // 默认数量
      show: true,
      zIndex: 2,
      img: {
        replace: false,  // false 默认图 true 换图 需要填写httpUrl地址
        httpUrl: 'http://www.zpzpup.com/assets/image/sakura.png'     // 绝对路径
      }
    }]

**Comment by liuguoxings** [comment]
我num写的100，zIndex写的999，，，

**Comment by liuguoxings** [comment]
是不是没有那么大

**Comment by JabinPeng** [comment]
![image](https://user-images.githubusercontent.com/37999218/105325938-1cf14600-5c08-11eb-937d-bac33358bc82.png)
![image](https://user-images.githubusercontent.com/37999218/105325966-28447180-5c08-11eb-87ef-6ab08086e831.png)

**Comment by JabinPeng** [comment]
可以的话 吧你的config。js 和packjson发我看看 690996726@qq.com

**Comment by liuguoxings** [comment]
我从QQ发你了，我在reco群里

**Comment by JabinPeng** [comment]
插件导出的['Sakura']   
配置需要用二维数组接收
"plugins": [
    ["sakura", {
    num: 50, // 默认数量
    show: true,
    zIndex: 2,
    img: {
    replace: false, // false 默认图 true 换图 需要填写httpUrl地址
    httpUrl: 'http://www.zpzpup.com/assets/image/sakura.png' // 绝对路径
    }
    }]
]
